### ISSUE TITLE
VTO firestore data structure change

### ISSUE THREAD

**Issue by edalford11** [TheFittingRoom/shop-sdk#27]
In order to allow users to do many VTOs at the same time and also reuse previous VTOs, the data structure in firestore will need a minor change.

Instead of
```json
{
  "vto": {
    "colorway_id": 123,
    "sku": 123-456-7890,
    "frames": [...]
  }
}
```

we should begin using
```json
{
  "vto": {
    "1": {
      "123-456-7890": {
        "colorway_id": 123,
        "frames": [...]
      }
    }
  }
}
```

Where 1 is the brand id and 123-456-7890 is the colorway sku.

This change relies on the backend PR https://github.com/TheFittingRoom/tfr-backend/pull/191

**Comment by codeliger** [comment]
done
