### ISSUE TITLE
Use `label` field for size recommendation message if its not empty

### ISSUE THREAD

**Issue by edalford11** [TheFittingRoom/shop-sdk#33]
The size recommendation endpoint has a new field on every size called `label`. If that field is not empty in the size recommendation api response, it should be used in the message when telling the user what the recommended sizes are for them. So instead of using the `size` field in the `size_value` object, you would use the `label` field on the size object instead.

To test this, you can use style id 1, which has a custom `label` for all sizes in the dev environment.

**Comment by codeliger** [comment]
implemented
