### ISSUE TITLE
[fix] Multiple requests on 360° View Component

### ISSUE THREAD

**Issue by matheuslino** [TheFittingRoom/shop-sdk#61]
**What?**
- Whenever the user changes the avatar perspective (slider component), the SDK triggers a new request for the asset.
    - Unnecessary requests = waste of resources

- ![Image](https://user-images.githubusercontent.com/6888192/235266235-68e493ab-4711-4be1-a3e2-918c9d9603f1.gif)

---
**Where?**
- Shop-SDK, avatar container

**Comment by codeliger** [comment]
not an issue
