### ISSUE TITLE
[fix] Date of birth is not persisted

### ISSUE THREAD

**Issue by matheuslino** [TheFittingRoom/shop-sdk#62]
**What?**

- The date of birth is not being persisted in the database properly (even after changing the select)
- 
    
    ![https://user-images.githubusercontent.com/6888192/235268086-f32695b7-910c-4275-b00d-6dee89acb293.gif](https://user-images.githubusercontent.com/6888192/235268086-f32695b7-910c-4275-b00d-6dee89acb293.gif)
    

---

**Where?**

- Mobile (IOS): Sign Up and Update Profile page

**Comment by codeliger** [comment]
not related to shop sdk
